Aplicacion/urls.py
from django.urls import path
from . import views


urlpatterns = [
     # Latido
     # Presentacion
     path('', views.menuInfo, name='Menu_Presentacion'),
     path('Sin_Servicio/', views.NoPago, name='SinServicio'),
    
]

Ganadera/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('Aplicacion.urls', 'Aplicacion'), namespace='aplicacion')),
    path('Catalogo/', include(('Catalogo.urls', 'Catalogo'), namespace='catalogo')),
    path('Descargas/', include(('Descargas.urls', 'Descargas'), namespace='descargas')),
    path('Proceso/', include(('Proceso.urls', 'Proceso'), namespace='proceso')),
    path('Subtabla/', include(('Subtabla.urls', 'Subtabla'), namespace='subtabla')),
]

Proceso/urls.py
from django.urls import path
from . import views
from Proceso.consultarProcesos import actualizar, agregar, editar, mostrar, formulario, dispositivos, excel


urlpatterns = [
    path('', views.homeProcesos, name='Inicio'),
    path('api/config/', dispositivos.obtener_comando, name='Dispositivos'),

    # DATOS DEL AREA DE SERVIDOS
    path('Solicitud_Servidos/', mostrar.TablaSolicitudServido, name='T_Solicitud_Servidos'),
    path('Corrales_Servidos/', mostrar.TablaServidoCorral, name='T_Corrales_Servidos'),
    path('exportar-servido-corral/', excel.ExportarServidoCorralExcel, name='exportar_servido_corral'),
    path('Consolidacion_Servido/', mostrar.TablaConsolidacionServido, name='T_Consolidacion'),
    path('Consolidacion_Servido/Filtro/Tolva/<str:ID>/<int:Estatus>/<int:Producto>/', mostrar.TablaTolvaServido),
    path('Consolidacion_Servido_Filtro/', mostrar.TablaFiltroServido, name='FT_Consolidacion'),
    path('Servidos_Manuales/', mostrar.TablaServidoAnimales, name='T_Servidos'),
    
    path('Tolva_Servido/', mostrar.TablaTolva, name='T_Tolva_Servido'),
    path('Tolva_Servido_Se_Sirve/', mostrar.TablaTolvaServidoCorral, name='T_Se_Sirve'),
    
    # FORMULADO
    path('Consolidacion_Formulacion/', mostrar.TablaConsolidacionFormulado, name='T_FConsolidacion'),
    path('Consolidacion_Formulado_Filtro/', mostrar.TablaFiltroFormulado, name='FT_FConsolidacion'),
    path('Formulado_Manuales/', mostrar.TablaFormuladoManual, name='T_FormuladoM'),
    path('Formulado_Servidos/', mostrar.TablaFormuladoCorral, name='T_Formulado_Servidos'),
    
    # DATOS DE LOS DATOS DE LA TOLVA
    path('Cargamento_Tolva/', mostrar.TablaCargamentoTolva, name='T_Cargamento_Tolva'),
    

    path('Formulario_Solicitud_Servido/',formulario.FormularioSolicitudServido, name='F_Solicitud_Servidos'),
    path('Formulario_Servidos_Manuales/',formulario.FormularioServidoAnimales, name='F_Servidos'),

    path('Guardar_Solicitud_Servidos/', agregar.guardarSolicitudServido, name="G_Solicitud_Servidos"),
    path('Guardar_Servidos_Manual/', agregar.guardarServidosManuales),

    path('Solicitud_Servidos/Editar/<ID>', editar.editarSolicitudServidos),
    path('Dato_Servidos_Manuales/Editar/<ID>', editar.editarServidosManuales),

    # ACTUALIZAR PROCESOS
    path('ActualizarServidorManual/', actualizar.actualizarServidosManual, name="A_Solicitud_Servidos"),
    path('ActualizarServidorManualCantidad/', actualizar.actualizarCantidadServidosManual, name="Cantidad_servidos_manuales"),
    path('ActualizarFormuladoManualCantidad/', actualizar.actualizarCantidadFormuladoManual, name="Cantidad_Formulado_manuales"),
    path('ActualizarServidosATolva/', actualizar.actualizarServidosATolva, name="A_Servidos_Tolva"),
    path('ActualizarFormuladoATolva/', actualizar.actualizarFormuladoATolva, name="A_Formulado_Tolva"),

    path('ActualizarCancelarServidosVehiculos/', actualizar.actualizarCancelarTolva, name="A_Pedido_Tolva"),
    path('ActualizarCancelarFormuladoVehiculos/', actualizar.actualizarCancelarFormulado, name="A_Pedido_Formulado"),
    ]

Proceso/models.py
from django.db import models

# Create your models here.

Proceso/views.py
from django.shortcuts import render

# Create your views here.
def homeProcesos(request):
    return render(request, 'cliente/index.html')

Proceso/templates/SolicitudServido/edit.html
{% extends "base.html" %}
{% load static %}
{% block title %}CLIENTE{% endblock %}
{% block body %}
<!--**********************************
            Content body start
        ***********************************-->
{% block head %}PROCESO{% endblock %}
<div class="content-body">
    <div class="container-fluid">
        <div class="row" style="padding-right: 0 !important;">
            <div class="col-sm-12 col-xl-12 col-xxl-12" style="padding-right: 0 !important;">
                <div class="card">
                    <div class="card-header d-block d-sm-flex border-0">
                        <div class="me-3">
                            <h4 class="card-title mb-2">
                                <a href="{% url 'proceso:T_Solicitud_Servidos'%}">
                                    <i class="bi bi-arrow-left-circle text-black fs-28"></i>
                                </a>
                                <b>EDITAR SERVIDOS MANUALES #{{TEServidos.Folio}}</b>
                            </h4>
                        </div>
                    </div>
                    <hr>
                    <div class="card-body tab-content px-4 pt-2">
                        <div class="tab-pane active show fade" id="monthly" role="tabpanel">

                            <form action="{% url 'proceso:A_Solicitud_Servidos'%}" method="POST" autocomplete="off">
                                {% csrf_token %}
                                <div class="form-group">
                                    <input type="hidden" name="id" value="{{TEServidos.ID}}">
                                    <input type="hidden" name="folio" value="{{TEServidos.Folio}}">
                                    <input type="hidden" class="form-control" name="tecnico"
                                        value="{{ user.first_name }} {{user.last_name}}">
                                    <input type="hidden" name="servido" value="1">
                                    <div class="row">
                                        <div class="col-sm-12 col-md-12 col-lg col-xl mb-3">
                                            <h6 class="h6-form">CORRAL <label>*</label></h6>
                                            <select class="select2 form-control col-12" name="corral" id="corral-select"
                                                required>
                                                <option value="{{FiltradoCorral.ID}}">
                                                    --------{{FiltradoCorral.Descripcion}}--------
                                                </option>
                                                {% for Corral in FECorral %}
                                                <option value="{{ Corral.ID }}">{{ Corral.Descripcion }}</option>
                                                {% endfor %}
                                            </select>
                                        </div>

                                        <div class="col-sm-12 col-md-12 col-lg col-xl mb-3">
                                            <h6 class="h6-form">PRODUCTO <label>*</label></h6>
                                            <select class="select2 form-control col-12" name="producto" required>
                                                <option value="{{FiltradoProducto.ID}}">
                                                    --------{{FiltradoProducto.Descripcion}}--------
                                                </option>
                                                {% for Producto in FEProducto %}
                                                <option value="{{ Producto.ID }}">{{ Producto.Descripcion }}</option>
                                                {% endfor %}
                                            </select>
                                        </div>
                                        <input type="hidden" value="{{FiltradoEstatus.ID}}" name="estatus">

                                    </div>

                                    <div class="row">
                                        <div class="col-sm-12 col-md-12 col-lg col-xl mb-3">
                                            <h6 class="h6-form">CANTIDAD SOLICITADA <label>*</label></h6>
                                            <input type="number" name="cantidadSol"
                                                value="{{TEServidos.CantidadSolicitada}}" class="form-control input"
                                                placeholder="Ingrese la cantidad solicitada (obligatorio)" required>
                                        </div>
                                        <div class="col-sm-12 col-md-12 col-lg col-xl mb-3">
                                            <h6 class="h6-form">FECHA SOLICITADA <label>*</label></h6>
                                            <input type="datetime-local" value="{{fecha|date:'Y-m-d H:i'}}"
                                                name="fechaSol" class="form-control input">
                                        </div>
                                    </div>


                                    <div class="row">
                                        <div class="col-sm-12 col-md-12 col-lg col-xl mb-3">
                                            <input type="hidden" name="cantidadSer"
                                                value="{{TEServidos.CantidadServida}}">
                                        </div>
                                        <div class="col-sm-12 col-md-12 col-lg col-xl mb-3">
                                            <input type="hidden" value="{{fechaServida|date:'Y-m-d H:i'}}"
                                                name="fechaSer">
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <button type="submit"
                                            class="btn btn-success buttonEnviar celular">Actualizar</button>
                                        <a href="{% url 'proceso:T_Solicitud_Servidos' %}"
                                            class="btn btn-danger buttonCancelar celular" role="button">Cancelar</a>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

Proceso/templates/SolicitudServido/form.html
{% extends "base.html" %}
{% load static %}
{% block title %}CLIENTE{% endblock %}
{% block body %}
<!--**********************************
            Content body start
        ***********************************-->
{% block head %}CATALOGO{% endblock %}
<div class="content-body">
    <div class="container-fluid">
        <div class="row" style="padding-right: 0 !important;">
            <div class="col-sm-12 col-xl-12 col-xxl-12" style="padding-right: 0 !important;">
                <div class="card">

                    <div class="card-header d-block d-sm-flex border-0">
                            <h4 class="card-title mb-2">
                                <a href="{% url 'proceso:T_Solicitud_Servidos'%}">
                                    <i class="bi bi-arrow-left-circle text-black fs-28"></i>
                                </a>
                                <b>FORMULARIO SOLICITUD SERVIDO</b>
                            </h4>
                    </div>
                    <hr>
                    <div class="card-body tab-content px-4 pt-2">
                        <div class="tab-pane active show fade" id="monthly" role="tabpanel">
                            <form action="{% url 'proceso:G_Solicitud_Servidos' %}" method="POST" autocomplete="off">
                                {% csrf_token %}
                                <div class="form-group">
                                    <div class="row">
                                        <input type="hidden" class="form-control" name="folio" value="{{ ultimo_folio }}">
                                        <input type="hidden" class="form-control" name="tecnico" value="{{ user.first_name }} {{user.last_name}}">
                                        <input type="hidden" class="form-control" name="peticion" value="1">
                                        <div class="col-sm-12 col-md-12 col-lg col-xl mb-3">
                                            <h6 class="h6-form">CORRAL *</h6>
                                            <select class="select2 form-control" style="width: 100%;" name="corral"
                                                id="corral-select" required>
                                                {% if SelectCorral %}
                                                <option value="{{ SelectCorral.ID }}">
                                                    ---------{{ SelectCorral.Descripcion }}---------
                                                </option>
                                                {% for Corrales in FECorrales %}
                                                <option value="{{ Corrales.ID }}">{{ Corrales.Descripcion }}</option>
                                                {% endfor %}
                                                {% else %}
                                                <option value="">SELECCIONE UN CORRAL</option>
                                                {% for Corrales in FECorrales %}
                                                <option value="{{ Corrales.ID }}">{{ Corrales.Descripcion }}</option>
                                                {% endfor %}
                                                {% endif %}
                                            </select>
                                        </div>

                                        <div class="col-sm-12 col-md-12 col-lg col-xl mb-3">
                                            <h6 class="h6-form">PRODUCTO *</h6>
                                            <select class="select2 form-control col-12" name="producto" required>
                                                {% if SelectProducto %}
                                                <option value="{{ SelectProducto.ID }}">
                                                    ---------{{ SelectProducto.Descripcion }}---------
                                                </option>
                                                {% for Producto in FEProductos %}
                                                <option value="{{ Producto.ID }}">{{ Producto.Descripcion }}</option>
                                                {% endfor %}
                                                {% else %}
                                                <option value="">SELECCIONE UN PRODUCTO</option>
                                                {% for Producto in FEProductos %}
                                                <option value="{{ Producto.ID }}">{{ Producto.Descripcion }}</option>
                                                {% endfor %}
                                                {% endif %}
                                            </select>
                                        </div>


                                        <div class="col-sm-12 col-md-12 col-lg col-xl mb-3">
                                            <h6 class="h6-form">CANTIDAD SOLICITADA *</h6>
                                            <input type="number" name="cantidadSol" class="form-control input"
                                                placeholder="Ingrese la cantidad solicitada (obligatorio)" required
                                                step="0.01">
                                        </div>

                                    </div>
                                    <input type="hidden" name="cantidadSer" value="0">
                                    <input type="hidden" name="prioridad" value="Media">
                                    <input type="hidden" name="estatus" value="3">
                                    <input type="hidden" name="fechaSol" value="{{FechaDeHoy}}">
                                    <input type="hidden" name="fechaSer" value="{{FechaDeHoy}}">
                                </div>
                                <div class="form-group">
                                    <button type="submit" class="btn btn-primary agregarBoton" name="agregar"
                                        id="agregarBoton">Guardar
                                        y agregar otro</button>
                                    <button type="submit" class="btn btn-success salirBoton" name="salir"
                                        id="salirBoton">Guardar y
                                        salir</button>
                                    <a href="{% url 'proceso:T_Solicitud_Servidos' %}">
                                        <button type="button" class="btn btn-danger cancelarBoton">Cancelar</button>
                                    </a>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<script>
    $(document).ready(function () {
        $('#corral-select').change(function () {
            var corralId = $(this).val();
            var url = '/obtener_clientes/' + corralId + '/';
            console.log(corralId)
            $.ajax({
                url: url,
                type: 'GET',
                success: function (data) {
                    $('#cliente-select').empty();

                    $.each(data.clientes, function (index, cliente) {
                        $('#cliente-select').append('<option value="' + cliente.ID + '">' + cliente.Nombre + '</option>');
                    });
                }
            });
        });
    });
</script>


{% endblock %}

Proceso/templates/SolicitudServido/index.html
{% extends "base.html" %}
{% load static %}
{% block title %}SERVIDOS{% endblock %}
{% block body %}
<!--**********************************
            Content body start
        ***********************************-->
{% block head %}PROCESO: SERVIDO{% endblock %}
<div class="content-body">
    <div class="container-fluid">
        <div class="row" style="padding-right: 0 !important;">
            <div class="col-sm-12 col-xl-12 col-xxl-12" style="padding-right: 0 !important;">
                <div class="card">

                    <div class="card-header d-block border-0">
                        <div class="row">
                            <div class="col-8">
                                <h4 class="card-title mb-1 d-flex align-items-center">
                                    <a href="{% url 'aplicacion:Menu_Presentacion' %}#Proceso" class="me-2">
                                        <i class="bi bi-arrow-left-circle text-black fs-28"></i>
                                    </a>
                                    <b>SERVIDOS: </b> - REQUERIMIENTO DE SERVIDOS
                                </h4>

                            </div>

                            <!-- BOTÓN -->
                            <div class="col-4 d-flex justify-content-md-end justify-content-start mt-3 mt-md-0">
                                <a href="{% url 'proceso:F_Solicitud_Servidos' %}">
                                    <button class="c-button">
                                        <span class="c-main">
                                            <span class="c-ico"><span class="c-blur"></span> <span
                                                    class="ico-text">+</span></span>
                                            Agregar
                                        </span>
                                    </button>
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="card-body tab-content p-0">
                        <div class="card-tabs my-5 mt-sm-0 px-5 mx-3">
                            <ul class="nav nav-tabs w-100 d-flex justify-content-between">
                                <li class="nav-item">
                                    <a class="nav-link active">Corrales pendientes</a>
                                </li>
                                <li class="nav-item">
                                    <a href="{% url 'proceso:FT_Consolidacion' %}" class="nav-link">Cargar en tolva</a>
                                </li>
                                <li class="nav-item">
                                    <a href="{% url 'proceso:T_Servidos' %}" class="nav-link">Captura manual</a>
                                </li>
                                <li class="nav-item">
                                    <a href="{% url 'proceso:T_Corrales_Servidos' %}" class="nav-link">Corrales
                                        servidos</a>
                                </li>
                            </ul>
                        </div>
                        <div class="tab-pane active show fade" id="monthly" role="tabpanel">
                            <div class="table-responsive">
                                <table class="table table-responsive-md card-table transactions-table" id="miTabla">
                                    <thead>
                                        <tr>
                                            <th class="text-black fs-16 font-w600 th-responsive">
                                                FOLIO
                                            </th>
                                            <th class="text-black fs-16 font-w600 th-responsive">
                                                CORRAL
                                            </th>
                                            <th class="text-black fs-16 font-w600 th-responsive">
                                                PRODUCTO
                                            </th>
                                            <th class="text-black fs-16 font-w600 th-responsive">
                                                CANTIDAD
                                            </th>
                                            <th class="text-black fs-16 font-w600 th-responsive">
                                                FECHA PETICION
                                            </th>
                                            <!-- <th class="text-black fs-16 font-w600 th-responsive">
                                                FECHA A SERVIR
                                            </th> -->

                                            <th class="text-black fs-16 font-w600 th-responsive">
                                                ACCIÓN
                                            </th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for Dato in TServidos %}
                                        <tr>
                                            <td>
                                                <span class="fs-16 text-black font-w400">
                                                    {{Dato.Folio}}
                                                </span>
                                            </td>
                                            <td>
                                                <span class="fs-16 text-black font-w400">
                                                    {{Dato.IDCorral_id__Descripcion}}
                                                </span>
                                            </td>
                                            <td>
                                                <span class="fs-16 text-black font-w400">
                                                    {{Dato.IDProducto_id__Descripcion}}
                                                </span>
                                            </td>
                                            <td>
                                                <span class="fs-16 text-black font-w400">
                                                    {{Dato.CantidadSolicitada}}
                                                </span>
                                            </td>
                                            <td>
                                                <span class="fs-16 text-black font-w400">
                                                    {{Dato.Fecha}}
                                                </span>
                                            </td>
                                            <!-- <td>
                                                <span class="fs-16 text-black font-w400">
                                                    {{Dato.FechaAServir}}
                                                </span>
                                            </td> -->
                                            <td>
                                                <a style="display: inline-block;" href="Editar/{{Dato.ID}}"
                                                    role="button">
                                                    <button class="edit-button">
                                                        <svg class="edit-svgIcon" viewBox="0 0 512 512">
                                                            <path
                                                                d="M410.3 231l11.3-11.3-33.9-33.9-62.1-62.1L291.7 89.8l-11.3 11.3-22.6 22.6L58.6 322.9c-10.4 10.4-18 23.3-22.2 37.4L1 480.7c-2.5 8.4-.2 17.5 6.1 23.7s15.3 8.5 23.7 6.1l120.3-35.4c14.1-4.2 27-11.8 37.4-22.2L387.7 253.7 410.3 231zM160 399.4l-9.1 22.7c-4 3.1-8.5 5.4-13.3 6.9L59.4 452l23-78.1c1.4-4.9 3.8-9.4 6.9-13.3l22.7-9.1v32c0 8.8 7.2 16 16 16h32zM362.7 18.7L348.3 33.2 325.7 55.8 314.3 67.1l33.9 33.9 62.1 62.1 33.9 33.9 11.3-11.3 22.6-22.6 14.5-14.5c25-25 25-65.5 0-90.5L453.3 18.7c-25-25-65.5-25-90.5 0zm-47.4 168l-144 144c-6.2 6.2-16.4 6.2-22.6 0s-6.2-16.4 0-22.6l144-144c6.2-6.2 16.4-6.2 22.6 0s6.2 16.4 0 22.6z">
                                                            </path>
                                                        </svg>
                                                    </button>
                                                </a>

                                            </td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}