Aplicacion/urls.py
from django.urls import path
from . import views


urlpatterns = [
     # Latido
     # Presentacion
     path('', views.menuInfo, name='Menu_Presentacion'),
     path('Sin_Servicio/', views.NoPago, name='SinServicio'),
    
]

Catalogo/urls.py
from django.urls import path
from . import views
from Catalogo.consultasCatalogo import actualizar, agregar, editar, mostrar, formulario


urlpatterns = [
   path('', views.homeCatalogos, name='Inicio'),
   
   # Tablas
   path('Operadores/', mostrar.TablaOperadores, name='T_Operador'),
   path('Materias_Primas/', mostrar.TablaMateriasPrimas, name='T_MateriaPrima'),
   path('Productos/', mostrar.TablaProductos, name='T_Producto'),
   path('Productos/Agregar/<ID>',mostrar.AgregarRecetas, name='AR_Producto'),   
   path('Corrales/', mostrar.TablaCorrales, name='T_Corral'),
   path('Tolvas/', mostrar.TablaTolva, name='T_Tolva'),
   
   # Formulario
   path('Formulario_Operadores/', formulario.FormualrioOperadores, name='F_Operador'),
   path('Formulario_Materias_Primas/', formulario.FormualrioMateriasPrimas, name='F_MateriaPrima'),

   path('Formulario_Productos/', formulario.FormualrioProductos, name='F_Producto'),
   path('Formulario_Corrales/', formulario.FormualrioCorrales, name='F_Corral'),
   path('Formulario_Tolvas/', formulario.FormualrioTolva, name='F_Tolva'),   
   
   # Guardar
   path('Guardar_Operadores/', agregar.guardarOperador, name='G_Operador'),
   path('Guardar_Materias_Primas/', agregar.guardarMateriasPrimas, name='G_MateriaPrima'),
   path('Guardar_Receta/', agregar.guardarRecetas, name='G_Receta'),
   path('Guardar_Productos/', agregar.guardarProductos, name='G_Producto'),
   path('Guardar_Corrales/', agregar.guardarCorrales, name='G_Corral'),
   path('Guardar_Tolvas/', agregar.guardarTolva, name='G_Tolva'),   

   #Editar
   path('Operadores/Editar/<ID>', editar.editarOperador, name='E_Operador'),
   path('Materias_Primas/Editar/<ID>', editar.editarMateriaPrima, name='E_MateriaPrima'),
   path('Productos/Editar/<ID>', editar.editarProducto, name='E_Producto'),
   path('Productos/Agregar/Editar/<ID>',editar.editarProductoReceta, name='ER_Producto'),
   path('Corrales/Editar/<ID>', editar.editarCorral, name='E_Corral'),
   path('Tolvas/Editar/<ID>', editar.editarTolva, name='E_Tolva'),   

   # Actualizar
   path('Actualizar_Operadores/', actualizar.actualizarOperador, name='A_Operador'),
   path('Actualizar_Materias_Primas/', actualizar.actualizarMateriaPrima, name='A_MateriaPrima'),
   path('Actualizar_Productos/', actualizar.actualizarProductos, name='A_Producto'),
   path('Actualizar_Recetas/', actualizar.actualizarRecetasProductos, name='A_Recetas'),
   path('Actualizar_Corrales/', actualizar.actualizarCorral, name='A_Corral'),
   path('Actualizar_Tolvas/', actualizar.actualizarTolva, name='A_Tolva'),   
]

Ganadera/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('Aplicacion.urls', 'Aplicacion'), namespace='aplicacion')),
    path('Catalogo/', include(('Catalogo.urls', 'Catalogo'), namespace='catalogo')),
    path('Descargas/', include(('Descargas.urls', 'Descargas'), namespace='descargas')),
    path('Proceso/', include(('Proceso.urls', 'Proceso'), namespace='proceso')),
    path('Subtabla/', include(('Subtabla.urls', 'Subtabla'), namespace='subtabla')),
]

Proceso/urls.py
from django.urls import path
from . import views
from Proceso.consultarProcesos import actualizar, agregar, editar, mostrar, formulario, dispositivos, excel


urlpatterns = [
    path('', views.homeProcesos, name='Inicio'),
    path('api/config/', dispositivos.obtener_comando, name='Dispositivos'),

    # DATOS DEL AREA DE SERVIDOS
    path('Solicitud_Servidos/', mostrar.TablaSolicitudServido, name='T_Solicitud_Servidos'),
    path('Corrales_Servidos/', mostrar.TablaServidoCorral, name='T_Corrales_Servidos'),
    path('exportar-servido-corral/', excel.ExportarServidoCorralExcel, name='exportar_servido_corral'),
    path('Consolidacion_Servido/', mostrar.TablaConsolidacionServido, name='T_Consolidacion'),
    path('Consolidacion_Servido/Filtro/Tolva/<str:ID>/<int:Estatus>/<int:Producto>/', mostrar.TablaTolvaServido),
    path('Consolidacion_Servido_Filtro/', mostrar.TablaFiltroServido, name='FT_Consolidacion'),
    path('Servidos_Manuales/', mostrar.TablaServidoAnimales, name='T_Servidos'),
    
    path('Tolva_Servido/', mostrar.TablaTolva, name='T_Tolva_Servido'),
    path('Tolva_Servido_Se_Sirve/', mostrar.TablaTolvaServidoCorral, name='T_Se_Sirve'),
    
    # FORMULADO
    path('Consolidacion_Formulacion/', mostrar.TablaConsolidacionFormulado, name='T_FConsolidacion'),
    path('Consolidacion_Formulado_Filtro/', mostrar.TablaFiltroFormulado, name='FT_FConsolidacion'),
    path('Formulado_Manuales/', mostrar.TablaFormuladoManual, name='T_FormuladoM'),
    path('Formulado_Servidos/', mostrar.TablaFormuladoCorral, name='T_Formulado_Servidos'),
    
    # DATOS DE LOS DATOS DE LA TOLVA
    path('Cargamento_Tolva/', mostrar.TablaCargamentoTolva, name='T_Cargamento_Tolva'),
    

    path('Formulario_Solicitud_Servido/',formulario.FormularioSolicitudServido, name='F_Solicitud_Servidos'),
    path('Formulario_Servidos_Manuales/',formulario.FormularioServidoAnimales, name='F_Servidos'),

    path('Guardar_Solicitud_Servidos/', agregar.guardarSolicitudServido, name="G_Solicitud_Servidos"),
    path('Guardar_Servidos_Manual/', agregar.guardarServidosManuales),

    path('Solicitud_Servidos/Editar/<ID>', editar.editarSolicitudServidos),
    path('Dato_Servidos_Manuales/Editar/<ID>', editar.editarServidosManuales),

    # ACTUALIZAR PROCESOS
    path('ActualizarServidorManual/', actualizar.actualizarServidosManual, name="A_Solicitud_Servidos"),
    path('ActualizarServidorManualCantidad/', actualizar.actualizarCantidadServidosManual, name="Cantidad_servidos_manuales"),
    path('ActualizarFormuladoManualCantidad/', actualizar.actualizarCantidadFormuladoManual, name="Cantidad_Formulado_manuales"),
    path('ActualizarServidosATolva/', actualizar.actualizarServidosATolva, name="A_Servidos_Tolva"),
    path('ActualizarFormuladoATolva/', actualizar.actualizarFormuladoATolva, name="A_Formulado_Tolva"),

    path('ActualizarCancelarServidosVehiculos/', actualizar.actualizarCancelarTolva, name="A_Pedido_Tolva"),
    path('ActualizarCancelarFormuladoVehiculos/', actualizar.actualizarCancelarFormulado, name="A_Pedido_Formulado"),
    ]

Aplicacion/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.models import Permission, AbstractBaseUser, BaseUserManager
    
class tblConfiguracion(models.Model):
    ID = models.AutoField(primary_key=True)
    Usuario = models.CharField(max_length=150, null=True)
    BaseDeDatos = models.CharField(max_length=150,null=True)
    FechaDescarga = models.DateTimeField(null=True)
    FechaActualizacion = models.DateTimeField(max_length=150, null=True)
    FolioSalMaquila = models.CharField(max_length=10, null=True)
    
    
        
# -------------------------------------------------------SUBTABLAS-------------------------------------------------------
class tblEstatus(models.Model):
    ID = models.AutoField(primary_key=True)
    Clave = models.CharField(max_length=15, null=True)
    Descripcion = models.CharField(max_length=150,null=True)
    
class tblUnidades(models.Model):
    ID = models.AutoField(primary_key=True)
    Clave = models.CharField(max_length=15, null=True)
    Descripcion = models.CharField(max_length=150,null=True)
    Abreviacion = models.CharField(max_length=150,null=True)
    
    
# -------------------------------------------------------CATALOGOS-------------------------------------------------------
class tblOperadores(models.Model):
    ID = models.AutoField(primary_key=True)
    Clave = models.CharField(max_length=15, null=True)
    Descripcion = models.CharField(max_length=150, null=True)
    IDEstatus = models.ForeignKey(tblEstatus, on_delete=models.DO_NOTHING, null=True)

class tblMateriaPrima(models.Model):
    ID = models.AutoField(primary_key=True)
    Clave = models.CharField(max_length=15, null=True)
    Descripcion = models.CharField(max_length=150,null=True)
    IDEstatus = models.ForeignKey(tblEstatus, on_delete=models.DO_NOTHING, null=True)
    IDUnidadMedida = models.ForeignKey(tblUnidades, on_delete=models.DO_NOTHING, null=True)
    PrecioUnitario = models.FloatField(null=True)
    Merma = models.FloatField(null=True)
    
class tblProductos(models.Model):
    ID = models.AutoField(primary_key=True)
    Clave = models.CharField(max_length=15, null=True)
    Descripcion = models.CharField(max_length=150,null=True)
    IDEstatus = models.ForeignKey(tblEstatus, on_delete=models.DO_NOTHING, null=True)
    IDUnidadMedida = models.ForeignKey(tblUnidades, on_delete=models.DO_NOTHING, null=True)
    PrecioUnitario = models.FloatField(null=True)
    SeSirve = models.CharField(max_length=15, null=True)
    
class tblCorrales(models.Model):
    ID = models.AutoField(primary_key=True)
    Clave = models.CharField(max_length=150, null=True)
    Descripcion = models.CharField(max_length=150,null=True)
    IDEstatus = models.ForeignKey(tblEstatus, on_delete=models.DO_NOTHING, null=True)
    Fecha = models.DateTimeField(max_length=150, null=True)     
   
class tblTolva(models.Model):
    ID = models.AutoField(primary_key=True)
    Clave = models.CharField(max_length=15, null=True)
    Marca = models.CharField(max_length=15, null=True)
    Modelo = models.CharField(max_length=150, null=True)
    IDEstatus = models.ForeignKey(tblEstatus, on_delete=models.DO_NOTHING, null=True)
    IDProducto = models.ForeignKey(tblProductos, on_delete=models.DO_NOTHING, null=True)
    Capacidad = models.IntegerField(null=True)
    UdeM = models.ForeignKey(tblUnidades, on_delete=models.DO_NOTHING, null=True)
    Alias = models.CharField(max_length=100, null=True)
    
class tblRepartidor(models.Model):
    ID = models.AutoField(primary_key=True)
    Folio = models.CharField(max_length=15, null=True)
    IDCorral = models.ForeignKey(tblCorrales, on_delete=models.DO_NOTHING, null=True)
    IDProducto = models.ForeignKey(tblProductos, on_delete=models.DO_NOTHING, null=True)
    IDEstatus = models.ForeignKey(tblEstatus, on_delete=models.DO_NOTHING, null=True)
    IDTolva = models.ForeignKey(tblTolva, on_delete=models.DO_NOTHING, null=True)
    CantidadSolicitada = models.IntegerField(null=True)
    CantidadServida = models.IntegerField(null=True)
    Fecha = models.DateTimeField(max_length=150, null=True)
    FechaServida = models.DateTimeField(max_length=150, null=True)


  
    
class tblFormulado(models.Model):
    ID = models.AutoField(primary_key=True)
    Folio = models.CharField(max_length=15, null=True)
    IDMateriaPrima = models.ForeignKey(tblMateriaPrima, on_delete=models.DO_NOTHING, null=True)
    IDProducto = models.ForeignKey(tblProductos, on_delete=models.DO_NOTHING, null=True)
    IDEstatus = models.ForeignKey(tblEstatus, on_delete=models.DO_NOTHING, null=True)
    IDTolva = models.ForeignKey(tblTolva, on_delete=models.DO_NOTHING, null=True)
    Proporcion = models.FloatField(null=True)
    CantidadSolicitada = models.CharField(max_length=15, null=True)
    CantidadServida = models.FloatField(null=True)
    Fecha = models.DateTimeField(max_length=150, null=True)
    FechaServida = models.DateTimeField(max_length=150, null=True)    
     
class tblReceta(models.Model):
    ID = models.AutoField(primary_key=True)
    Folio = models.CharField(max_length=15, null=True)
    IDMateriaPrima = models.ForeignKey(tblMateriaPrima, on_delete=models.DO_NOTHING, null=True)
    IDProductos = models.ForeignKey(tblProductos, on_delete=models.DO_NOTHING, null=True)
    Porcentaje = models.FloatField(null=True)
    Merma = models.FloatField(null=True)
    


class Control(models.Model):
    # Nombre del dispositivo
    ID = models.AutoField(primary_key=True)
    IDDispositivo = models.ForeignKey(tblTolva, on_delete=models.DO_NOTHING, null=True)
    Alias = models.CharField(max_length=100)
    Estatus = models.BooleanField(default=True)
    Token = models.CharField(max_length=100, unique=True)
    Movil = models.BooleanField(default=True)
    ComBau = models.IntegerField()
    
    IPBaseDatos = models.CharField(max_length=100, default="default")
    userMysql = models.CharField(max_length=100, default="default")
    passMysql = models.CharField(max_length=100, default="default")
    puerto = models.CharField(max_length=100, default="default")
    namebase = models.CharField(max_length=100, default="default")
    
    comando_pendiente = models.CharField(max_length=50, blank=True, null=True)
    ultima_conexion = models.DateTimeField(auto_now=True)
    
    
    
    
class tblServiciosWeb(models.Model):
    ID = models.AutoField(primary_key=True)
    Servicio = models.BooleanField(True, null=True)
    EstadoPago = models.BooleanField(True, null=True)
    FechaVencimiento = models.DateField(null=True)
    Notificacion = models.BooleanField(True, null=True)

Catalogo/models.py
from django.db import models

# Create your models here.

Catalogo/views.py
from django.shortcuts import render

# Create your views here.
def homeCatalogos(request):
    return render(request, 'cliente/index.html')

Catalogo/templates/MateriaPrima/edit.html
{% extends "base.html" %}
{% load static %}
{% block title %}CLIENTE{% endblock %}
{% block body %}
<!--**********************************
            Content body start
        ***********************************-->
{% block head %}CATALOGO{% endblock %}
<div class="content-body">
    <div class="container-fluid">
        <div class="row" style="padding-right: 0 !important;">
            <div class="col-sm-12 col-xl-12 col-xxl-12" style="padding-right: 0 !important;">
                <div class="card">
                    <div class="card-header d-block d-sm-flex border-0">
                        <div class="me-3">
                            <h4 class="card-title mb-2">
                                <a href="{% url 'catalogo:T_MateriaPrima'%}">
                                    <i class="bi bi-arrow-left-circle text-black fs-28"></i>
                                </a>
                                <b>EDITAR MATERIA PRIMA #{{TEMateriaPrima.Clave}}</b>
                                
                            </h4>
                            
                        </div>
                    </div>
                    <hr>
                    <div class="card-body tab-content px-4 pt-2">
                        <div class="tab-pane active show fade" id="monthly" role="tabpanel">
                            <form action="{% url 'catalogo:A_MateriaPrima'%}" method="POST" autocomplete="off">
                                {% csrf_token %}
                                <div class="form-group">
                                    <input type="hidden" name="id" value="{{TEMateriaPrima.ID}}">
                                    <input type="hidden" name="clave" value="{{TEMateriaPrima.Clave}}">
                                    <input type="hidden" class="form-control" name="tecnico"
                                        value="{{ user.first_name }} {{user.last_name}}">
                                    <div class="row">
                                        <div class="col-sm-12 col-md-12 col-lg-6 col-xl-6 mb-3">
                                            <h6 class="h6-form">MATERIA PRIMA *</h6>
                                            <input type="text" name="materia" value="{{TEMateriaPrima.Descripcion}}"
                                                class="form-control input" placeholder="Ingrese la materia prima"
                                                required>
                                        </div>
                                        <div class="col-sm-12 col-md-12 col-lg-4 col-xl-4 mb-3">
                                            <h6 class="h6-form">PRECIO UNITARIO *</h6>
                                            <input type="number" name="precio" value="{{TEMateriaPrima.PrecioUnitario}}"
                                                class="form-control input" placeholder="Ingrese el precio unitario"
                                                required step="0.01">
                                        </div>
                                        <div class="col-sm-12 col-md-12 col-lg-2 col-xl-2 mb-3">
                                            <h6 class="h6-form">MERMA *</h6>
                                            <input type="number" name="merma" value="{{TEMateriaPrima.Merma}}"
                                                class="form-control input" placeholder="Ingrese la merma" required
                                                step="0.01">
                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="col-sm-12 col-md-4 col-lg-6 col-xl-6 mb-3">
                                            <h6 class="h6-form">ESTATUS *</h6>
                                            <select class="select2 form-control col-12" name="estatus" required>
                                                <option value="{{FiltradoEstatus.ID}}">
                                                    --------{{FiltradoEstatus.Descripcion}}--------
                                                </option>
                                                {% for Estatus in FEEstatus %}
                                                <option value="{{ Estatus.ID }}">{{ Estatus.Descripcion }}</option>
                                                {% endfor %}
                                            </select>
                                        </div>
                                        <div class="col-sm-12 col-md-4 col-lg-6 col-xl-6 mb-3">
                                            <h6 class="h6-form">UNIDAD MEDIDA *</h6>
                                            <select class="select2 form-control col-12" name="unidad" required>
                                                <option value="{{FiltradoUnidad.ID}}">
                                                    --------{{FiltradoUnidad.Descripcion}}--------
                                                </option>
                                                {% for Unidad in FEUnidad %}
                                                <option value="{{ Unidad.ID }}">{{ Unidad.Descripcion }}</option>
                                                {% endfor %}
                                            </select>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <button type="submit" class="btn btn-success">Actualizar</button>
                                        <a href="{% url 'catalogo:T_MateriaPrima'%}" class="btn btn-danger">Cancelar</a>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

Catalogo/templates/MateriaPrima/index.html
{% extends "base.html" %}
{% load static %}
{% block title %}CLIENTE{% endblock %}
{% block body %}
<!--**********************************
            Content body start
        ***********************************-->
{% block head %}CATALOGO{% endblock %}
<div class="content-body">
    <div class="container-fluid">
        <div class="row" style="padding-right: 0 !important;">
            <div class="col-sm-12 col-xl-12 col-xxl-12" style="padding-right: 0 !important;">
                <div class="card">
                    <div class="card-header d-block  border-0">
                        <div class="row">
                            <div class="col-8">
                                <h4 class="card-title mb-1 d-flex align-items-center">
                                    <a href="{% url 'aplicacion:Menu_Presentacion' %}#Catalogo" class="me-2">
                                        <i class="bi bi-arrow-left-circle text-black fs-28"></i>
                                    </a>
                                    <b>TABLA MATERIA PRIMA</b>
                                </h4>
                               
                            </div>

                            <!-- BOTÓN -->
                            <div class="col-4 d-flex justify-content-md-end justify-content-start mt-3 mt-md-0">
                                <a href="{% url 'catalogo:F_MateriaPrima' %}">
                                    <button class="c-button">
                                        <span class="c-main">
                                            <span class="c-ico"><span class="c-blur"></span> <span class="ico-text">+</span></span>
                                            Agregar
                                        </span>
                                    </button>
                                </a>
                            </div>

                        </div>
                    </div>

                    <div class="card-body tab-content p-0">
                        <div class="tab-pane active show fade" id="monthly" role="tabpanel">
                            <div class="table-responsive">
                                <table class="table table-responsive-md card-table transactions-table" id="miTabla">
                                    <thead>
                                        <tr>
                                            <th class="text-black fs-16 font-w600 th-responsive">
                                                CLAVE
                                            </th>
                                            <th class="text-black fs-16 font-w600 th-responsive">
                                                MATERIA PRIMA
                                            </th>
                                            <th class="text-black fs-16 font-w600 th-responsive">
                                                ESTATUS
                                            </th>
                                            <th class="text-black fs-16 font-w600 th-responsive">
                                                UNIDAD MEDIDA
                                            </th>
                                            <th class="text-black fs-16 font-w600 th-responsive">
                                                PRECIO UNITARIO
                                            </th>
                                            <th class="text-black fs-16 font-w600 th-responsive">
                                                MERMA
                                            </th>
                                            {% if perms.Aplicacion.change_tblmateriaprima or perms.Aplicacion.delete_tblmateriaprima %}
                                            <th class="text-black fs-16 font-w600 th-responsive">
                                                ACCIÓN
                                            </th>
                                            {% endif %}
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for Dato in TMateriasPrimas %}
                                        <tr>
                                            <td>
                                                <span class="fs-16 text-black font-w400">
                                                    {{Dato.Clave}}
                                                </span>
                                            </td>
                                            <td>
                                                <span class="fs-16 text-black font-w400">
                                                    {{Dato.Descripcion}}
                                                </span>
                                            </td>
                                            <td>
                                                <span class="fs-16 text-black font-w400">
                                                    {{Dato.IDEstatus_id__Descripcion}}
                                                </span>
                                            </td>
                                            <td>
                                                <span class="fs-16 text-black font-w400">
                                                    {{Dato.IDUnidadMedida_id__Abreviacion}}
                                                </span>
                                            </td>
                                            <td>
                                                <span class="fs-16 text-black font-w400">
                                                    {{Dato.PrecioUnitario}}
                                                </span>
                                            </td>
                                            <td>
                                                <span class="fs-16 text-black font-w400">
                                                    {{Dato.Merma}}
                                                </span>
                                            </td>
                                             {% if perms.Aplicacion.change_tblmateriaprima or perms.Aplicacion.delete_tblmateriaprima %}
                                            <td>
                                                {% if perms.Aplicacion.change_tblmateriaprima %}
                                                <a style="display: inline-block;" href="Editar/{{Dato.ID}}">
                                                    <button class="edit-button">
                                                        <svg class="edit-svgIcon" viewBox="0 0 512 512">
                                                            <path
                                                                d="M410.3 231l11.3-11.3-33.9-33.9-62.1-62.1L291.7 89.8l-11.3 11.3-22.6 22.6L58.6 322.9c-10.4 10.4-18 23.3-22.2 37.4L1 480.7c-2.5 8.4-.2 17.5 6.1 23.7s15.3 8.5 23.7 6.1l120.3-35.4c14.1-4.2 27-11.8 37.4-22.2L387.7 253.7 410.3 231zM160 399.4l-9.1 22.7c-4 3.1-8.5 5.4-13.3 6.9L59.4 452l23-78.1c1.4-4.9 3.8-9.4 6.9-13.3l22.7-9.1v32c0 8.8 7.2 16 16 16h32zM362.7 18.7L348.3 33.2 325.7 55.8 314.3 67.1l33.9 33.9 62.1 62.1 33.9 33.9 11.3-11.3 22.6-22.6 14.5-14.5c25-25 25-65.5 0-90.5L453.3 18.7c-25-25-65.5-25-90.5 0zm-47.4 168l-144 144c-6.2 6.2-16.4 6.2-22.6 0s-6.2-16.4 0-22.6l144-144c6.2-6.2 16.4-6.2 22.6 0s6.2 16.4 0 22.6z">
                                                            </path>
                                                        </svg>
                                                    </button>
                                                </a>
                                                {% endif %}
                                            </td>
                                            {% endif %}
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}